/**
 * The block.
 *
 * The PHPUnit suite already proves the render callback returns the same markup
 * the shortcode returns, so repeating that here would buy nothing. What only a
 * browser can answer is whether the *built* JavaScript works: `build/` is
 * generated by bin/build and is not in the repository, so every assertion below
 * is also an assertion that the build ran and produced something a browser can
 * load.
 *
 * Two things are worth a browser, and nothing else here is:
 *
 * * the editor script loads and registers the block -- a broken build, a
 *   missing dependency in index.asset.php or a bad block.json all show up here
 *   and nowhere else, and the server-rendered preview additionally shows
 *   whether the editor got the stylesheet the shapes are masked from;
 * * a post holding the block renders the rating on the front end, which is the
 *   only place the name written into post_content is resolved by the real
 *   parser in a real request.
 */

const { test, expect } = require( '@wordpress/e2e-test-utils-playwright' );

const { uniqueTitle } = require( './helpers' );

/** The block this plugin registers. */
const BLOCK = 'wp-postratings/ratings';

test.describe( 'The block', () => {
	test.describe( 'in the editor', () => {
		test( 'is registered, under the prefixed name', async ( {
			admin,
			editor,
			page,
		} ) => {
			await admin.createNewPost();
			await editor.canvas.locator( 'body' ).waitFor();

			const names = await page.evaluate( () =>
				window.wp.blocks.getBlockTypes().map( ( type ) => type.name ),
			);

			// If the build did not run, or index.asset.php named a dependency
			// that does not exist, the editor script never executes and the
			// name is not here -- which is the failure this whole file exists
			// for.
			expect( names ).toContain( BLOCK );

			// The prefix is not decoration: a block name is written into
			// post_content and lives there for the life of the post.
			expect( names ).not.toContain( 'postratings/ratings' );
		} );

		test( 'previews the rating of the post it is given', async ( {
			admin,
			editor,
			requestUtils,
		} ) => {
			const post = await requestUtils.createPost( {
				title: uniqueTitle( 'Rated in a block' ),
				content: 'Something to rate.',
				status: 'publish',
			} );

			await admin.createNewPost();
			await editor.insertBlock( {
				name: BLOCK,
				attributes: { id: post.id },
			} );

			// The preview is core's ServerSideRender, which posts the
			// attributes to /wp/v2/block-renderer/ and draws what the front end
			// would draw. Seeing the rating here is what proves the block earns
			// no REST route of its own.
			await expect(
				editor.canvas.locator( `#wp-postratings-${ post.id }` ),
			).toBeVisible();

			// Every glyph is an empty <i> sized and masked entirely by the
			// front-end stylesheet, so an editor that does not enqueue it
			// previews the control as a row of labels with nothing beside them
			// -- the right markup and visibly not the rating the post will
			// show. An unstyled empty <i> is zero wide, so this is the
			// enqueue, asserted where a screenshot would have been needed
			// otherwise.
			const width = await editor.canvas
				.locator( `#wp-postratings-${ post.id } .wp-postratings-item` )
				.first()
				.evaluate( ( el ) => el.getBoundingClientRect().width );

			expect( width ).toBeGreaterThan( 0 );
		} );
	} );

	test.describe( 'on the front end', () => {
		test( 'a post holding the block renders the rating', async ( {
			page,
			requestUtils,
		} ) => {
			const post = await requestUtils.createPost( {
				title: uniqueTitle( 'A rating in a block' ),
				content: `<!-- wp:${ BLOCK } /-->`,
				status: 'publish',
			} );

			await page.goto( post.link );

			// No id attribute, so the block rates the post it sits in -- which
			// is the front end resolving the same default an empty [ratings]
			// resolves, in a real request rather than a fixture.
			await expect(
				page.locator( `#wp-postratings-${ post.id }` ),
			).toBeVisible();
		} );

		test( 'the block and the shortcode both render on one post', async ( {
			page,
			requestUtils,
		} ) => {
			const post = await requestUtils.createPost( {
				title: uniqueTitle( 'Both entry points at once' ),
				content: `<!-- wp:${ BLOCK } /-->\n\n[ratings]`,
				status: 'publish',
			} );

			await page.goto( post.link );

			// Same post, so both renders produce the same wrapper -- which is
			// the point: two entry points, one renderer. Two is what proves the
			// shortcode still works with a block on the same page.
			await expect(
				page.locator( `#wp-postratings-${ post.id }` ),
			).toHaveCount( 2 );
		} );
	} );
} );
